name: Generate Post Index

on:
  push:
    paths:
      - 'assets/post/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate assets/post/index.json
        run: python3 .github/scripts/generate_post_index.py

      - name: Commit & Push index.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/post/index.json
          git diff --cached --quiet || git commit -m "chore: update post index [skip ci]"
          git push